export const CHANGE_POMODORO = "CHANGE_POMODORO";
export const CHANGE_SHORT_BREAK = "CHANGE_SHORT_BREAK";
export const CHANGE_LONG_BREAK = "CHANGE_LONG_BREAK";
export const CHANGE_COUNT = "CHANGE_COUNT";